@OfficeSystem_HostAddress = http://localhost:5286
@host = https://localhost:7154

POST {{host}}/api/auth/register
Content-Type: application/json

{
  "Id": "test01",
  "Password": "1234",
  "Name": "홍길동",
  "CompanyNum": "EMP001"
}

###
